name: ActualTeleport
version: ${project.version}
main: dev.alve.actualteleport.actualteleport.ActualTeleport
api-version: 1.13
authors: [alvesvaren]
website: https://alve.dev/actualplugins

commands:
  bed:
    description: Teleports you to your bed.
    usage: /bed [player]
    permission: actualteleport.bed
  spawn:
    description: Teleports you to the spawn.
    usage: /spawn
    permission: actualteleport.spawn
  tpa:
    description: Teleports you to another player.
    usage: /tpa <player>
    permission: actualteleport.tpa
  tpyes:
    description: Accepts any teleportation requests from <player>
    usage: /tpyes <player>
    aliases:
      - tpy
      - tpaccept
      - tpallow
    permission: actualteleport.tpa
  debug:
    description: debug
    usage: /debug
    permission: actualteleport.debug

permissions:
  actualteleport.*:
    description: Gives you all permissions for actual teleport
    children:
      actualteleport.bed: true
      actualteleport.spawn: true
      actualteleport.death: true
      actualteleport.tpa: true
  actualteleport.debug:
    default: op
    description: test
  actualteleport.tpa:
    description: Allows you to teleport to another player
    default: true
  actualteleport.bed:
    description: Teleports you to the spawn.
    default: true
  actualteleport.spawn:
    description: Teleports you to the world spawn.
    default: true
