name: ActualHomes
main: info.evla.actualhomes.Plugin
version: 0.0.3
author: Evla03

commands:
  homes:
    description: Lists all homes owned by the player.
    usage: /<command> [player]
    permission: actualhomes.list
    permission-message: You don't have <permission>
  sethome:
    description: Sets a new home here.
    usage: /<command> [name] or /<command> [player]:[name]
    permission: actualhomes.set.self
  delhome:
    description: Deletes a home
    usage: /<command> [name] or /<command> [player]:[name]
  home:
    description: Teleport home
    usage: /<command> [name] or /<command> [player]:[name]
    aliases: [go, visit]
    permission: actualhomes.go.self

permissions:
  actualhomes.*:
    description: Gives access to all permissions in actual homes
    children:
      actualhomes.list.self: true
      actualhomes.list.other: true
      actualhomes.set.self: true
      actualhomes.set.other: true
      actualhomes.remove.self: true
      actualhomes.remove.other: true
      actualhomes.go.self: true
      actualhomes.go.other: true
      actualhomes.admin: true
      
    actualhomes.list.*:
      description: Gives permissions to list any player's homes
      children:
        actualhomes.list.self: true
        actualhomes.list.other: true
    actualhomes.list.self:
      description: Allows you to list your own homes
      default: true
    actualhomes.list.other:
      description: Allows you to list other players homes
      default: op
      
    actualhomes.set.*:
      description: Allows you to set a new home for any player
      children:
        actualhomes.set.self: true
        actualhomes.set.other: true    
    actualhomes.set.self:
      description: Allows you to set a new home for yourself
      default: true
    actualhomes.set.other:
      description: Allows you to set a new home for someone else
      default: op
      
    actualhomes.remove.*:
      description: Allows you to remove any player's home
      children:
        actualhomes.remove.self: true
        actualhomes.remove.other: true
    actualhomes.remove.self:
      description: Allows you to remove your own homes
      default: true
    actualhomes.remove.other:
      description: Allows you to remove other players homes
      default: op
      
    actualhomes.go.*:
      description: Allows you to teleport to any player's home
      children:
        actualhomes.go.self: true
        actualhomes.go.other: true
    actualhomes.go.self:
      description: Allows you to teleport to one of your own homes
      default: true
    actualhomes.go.other:
      description: Allows you to teleport to another players home
      default: op
      
    actualhomes.admin:
      description: Admin permission for actual homes
      default: op